### ISSUE TITLE
'import sass.Import._' problem

### ISSUE THREAD

**Issue by GlulkAlex** [widok/skeleton#3]
on `sbt assets`
have an error:

```
[info] Sass compiling on 1 source(s)
java.lang.Exception: 'sass' command not found. Try to add path to 'sass' to your $PATH system variable
```

Any suggestions how to properly resolve this ?

**Comment by tindzk** [comment]
Yes, you need to install sass first. See [sbt-sass](https://github.com/ShaggyYeti/sbt-sass#prerequisites) for more information.
